# ===============================
# DATABASE
# ===============================
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/autodb?useSSL=false
spring.datasource.username: root
spring.datasource.password: root
# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle: 5
spring.datasource.hikari.maximumPoolSize: 20
spring.datasource.hikari.idleTimeout: 30000
spring.datasource.hikari.poolName: SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime: 2000000
spring.datasource.hikari.connectionTimeout: 30000
#spring.datasource.type: com.zaxxer.hikari.HikariDataSource
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.jdbc.batch_size: 10
#spring.jpa.properties.hibernate.jdbc.fetch_size: 50
spring.jpa.properties.hibernate.format_sql: true
#spring.jpa.properties.hibernate.max_fetch_depth: 3
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update

# Enable logging
logging.level.org.hibernate.SQL: debug
  # Enable logging for HikariCP to verify that it is used
logging.level.com.zaxxer.hikari.HikariConfig: debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

server.servlet.context-path: /auto
server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json
